kind: volumeset
metadata:
  name: vs-0
  namespace: default
  annotations:
    cpln.io/resource-policy: keep
apiVersion: cpln.io/v1
description: vs-0 asdf
org: {{ .Values.org }}
gvc: fresh
tags: {}
spec:
  fileSystemType: ext4
  initialCapacity: 10
  performanceClass: general-purpose-ssd
  snapshots:
    createFinalSnapshot: true
    retentionDuration: "7d"
